// SPDX-License-Identifier: Apache-2.0
/**
 * Builds the Python Typed Accessor runtime that `varlatch types` embeds in
 * every Python module it generates: src/whatwg_url.py and src/runtime.py,
 * concatenated in that order, without their SPDX lines and without the lines
 * marked `# varlatch: embed-drop` (the import that joins them as separate
 * modules for testing). Written to dist/embedded.js as a string. The output
 * depends only on the sources, so one generator version always embeds the
 * same bytes.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCES = ["src/whatwg_url.py", "src/runtime.py"];

function embeddable(path) {
  const text = readFileSync(join(root, path), "utf8");
  if (/^from __future__ /m.test(text)) {
    throw new Error(`${path}: a __future__ import is only valid at the start of a module, and this code is embedded mid-module`);
  }
  if (/[^\x09\x0a\x20-\x7e]/.test(text)) {
    throw new Error(`${path}: the embedded runtime must be printable ASCII (use escapes in string literals)`);
  }
  const lines = text
    .split("\n")
    .filter((line) => !/^# SPDX-License-Identifier: /.test(line) && !line.includes("# varlatch: embed-drop"));
  // A module docstring would become a stray expression once embedded.
  const first = lines.find((line) => line.trim() !== "" && !line.startsWith("#"));
  if (first && /^[rRbBuU]?["']/.test(first)) throw new Error(`${path}: no module docstring; use a comment`);
  return lines.join("\n").trim();
}

export function buildRuntimeSource() {
  return `${SOURCES.map(embeddable).join("\n\n\n")}\n`;
}

/** The semantics versions the runtime implements, read from its one definition. */
export function implementedVersions() {
  const match = /^_IMPLEMENTED_VERSIONS = \(([0-9, ]+)\)$/m.exec(readFileSync(join(root, "src/runtime.py"), "utf8"));
  if (!match) throw new Error("src/runtime.py: _IMPLEMENTED_VERSIONS not found");
  return match[1].split(",").map((v) => v.trim()).filter(Boolean).map(Number);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const source = buildRuntimeSource();
  const header = "// Generated by packages/accessor-python/scripts/embed.mjs. Do not edit.\n";
  mkdirSync(join(root, "dist"), { recursive: true });
  writeFileSync(
    join(root, "dist", "embedded.js"),
    `${header}export const PYTHON_RUNTIME_SOURCE = ${JSON.stringify(source)};\nexport const PYTHON_IMPLEMENTED_SEMANTICS_VERSIONS = ${JSON.stringify(implementedVersions())};\n`,
  );
  writeFileSync(
    join(root, "dist", "embedded.d.ts"),
    `${header}/** The Python Typed Accessor runtime, embedded at the end of every generated Python module. */\nexport declare const PYTHON_RUNTIME_SOURCE: string;\n/** The Contract Semantics versions the Python runtime implements. */\nexport declare const PYTHON_IMPLEMENTED_SEMANTICS_VERSIONS: readonly number[];\n`,
  );
}
