// SPDX-License-Identifier: Apache-2.0
import { SKILL_FILES } from "./skillFiles.generated.js";

/**
 * The agent skill (ADR-0043 Decision 7): one agent-neutral skill in the open
 * Agent Skills format, embedded in the CLI so the installed copy always
 * matches the CLI that runs its commands. Source: apps/cli/skill/varlatch.
 */

export const SKILL_NAME = "varlatch";

/** `varlatch agents guide <topic>`: each topic is one reference file. */
export const GUIDE_TOPICS: Readonly<Record<string, string>> = {
  setup: "references/setup.md",
  run: "references/run.md",
  "agent-run": "references/agent-run.md",
  "self-hosting": "references/self-hosting.md",
  contract: "references/contract.md",
};

/** A reference file's first line: it is generated, and installing again overwrites edits. */
function generatedNote(version: string): string {
  return `<!-- Generated by varlatch ${version}: \`varlatch agents install\` overwrites edits to this file. -->\n`;
}

/**
 * The skill's files for this CLI version, by path inside the skill
 * directory: SKILL.md names the generator in its frontmatter's `metadata`
 * (a field the specification allows), each reference in a first-line note.
 */
export function skillFiles(version: string): Map<string, string> {
  const files = new Map<string, string>();
  for (const [path, content] of Object.entries(SKILL_FILES)) {
    files.set(path, path === "SKILL.md" ? content.replaceAll("{{VERSION}}", version) : generatedNote(version) + content);
  }
  return files;
}

/** SKILL.md without its frontmatter: what `varlatch agents guide` prints. */
function skillBody(): string {
  const content = SKILL_FILES["SKILL.md"] as string;
  const end = content.indexOf("\n---\n", 4);
  return content.slice(end + 5).replace(/^\n+/, "");
}

export class GuideTopicError extends Error {
  override name = "GuideTopicError";
}

/**
 * The skill, or one reference, for a coding agent with a shell but no skill
 * support. Reference paths in the skill are named as topics here.
 */
export function guide(topic: string | undefined): string {
  if (topic === undefined) {
    return `${skillBody().trimEnd()}\n\nTopics: ${Object.keys(GUIDE_TOPICS).join(", ")} (varlatch --assisted agents guide <topic>)\n`;
  }
  const path = GUIDE_TOPICS[topic];
  if (!path) throw new GuideTopicError(`no guide topic ${topic}; topics: ${Object.keys(GUIDE_TOPICS).join(", ")}`);
  return SKILL_FILES[path] as string;
}
