#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
/**
 * Embeds the agent skill (apps/cli/skill/varlatch) into the CLI build as
 * src/agents/skillFiles.generated.ts, so the installed skill always matches
 * the CLI that runs its commands (ADR-0043 Decision 7). Run after editing
 * the skill: pnpm --filter @varlatch/cli embed-skill. A test fails when the
 * generated module is stale.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const cliDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const skillDir = join(cliDir, "skill", "varlatch");

export function collectSkillFiles() {
  const files = {};
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) walk(path);
      else files[relative(skillDir, path).split("\\").join("/")] = readFileSync(path, "utf8");
    }
  };
  walk(skillDir);
  return files;
}

export function renderModule(files) {
  return [
    "// SPDX-License-Identifier: Apache-2.0",
    "// Generated by apps/cli/scripts/embed-skill.mjs from apps/cli/skill/varlatch. Do not edit.",
    `export const SKILL_FILES: Readonly<Record<string, string>> = ${JSON.stringify(files, null, 2)};`,
    "",
  ].join("\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const out = join(cliDir, "src", "agents", "skillFiles.generated.ts");
  writeFileSync(out, renderModule(collectSkillFiles()));
  console.log(`Wrote ${relative(cliDir, out)}`);
}
