# SPDX-License-Identifier: Apache-2.0
# Shared helpers for the Python Typed Accessor tests: paths, the vector files,
# the runtime as a module, and modules generated by the real CLI generator.
import importlib.util
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

PACKAGE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(os.path.dirname(PACKAGE))
SRC = os.path.join(PACKAGE, "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

import runtime  # noqa: E402

HASH_A = "sha256:" + "a" * 64
HASH_B = "sha256:" + "b" * 64


def vectors(relative: str) -> dict:
    with open(os.path.join(REPO, relative), encoding="utf-8") as f:
        return json.load(f)


def semantics_v2() -> dict:
    return vectors("packages/contract/test/vectors/semantics-v2.json")


def portability_v2() -> dict:
    return vectors("packages/contract/test/vectors/semantics-v2-portability.json")


def run_context_v1() -> dict:
    return vectors("packages/accessor/test/vectors/run-context-v1.json")


def ada_available() -> bool:
    return importlib.util.find_spec("ada_url") is not None


def check_ada_mode(case: unittest.TestCase) -> None:
    """CI names the dependency mode it means to test; fail if it is not the one running."""
    expected = os.environ.get("VARLATCH_EXPECT_ADA")
    if expected is not None:
        case.assertEqual(ada_available(), expected == "1", "the ada-url dependency mode is not the one CI asked for")


def node() -> "str | None":
    """The node binary for tests that need the reference implementation, or a skip."""
    found = shutil.which("node")
    if found is None:
        if os.environ.get("VARLATCH_REQUIRE_NODE") == "1":
            raise AssertionError("node is not on PATH, and VARLATCH_REQUIRE_NODE=1")
        raise unittest.SkipTest("node is not on PATH")
    return found


def built(path: str) -> str:
    full = os.path.join(REPO, path)
    if not os.path.exists(full):
        if os.environ.get("VARLATCH_REQUIRE_NODE") == "1":
            raise AssertionError(f"{path} is not built, and VARLATCH_REQUIRE_NODE=1")
        raise unittest.SkipTest(f"{path} is not built: run pnpm build")
    return full


def run_node(script: str, payload: object) -> object:
    binary = node()
    out = subprocess.run(
        [binary, "--input-type=module", "-e", script],
        input=json.dumps(payload),
        capture_output=True,
        text=True,
        cwd=REPO,
        check=False,
    )
    if out.returncode != 0:
        raise AssertionError(f"node failed:\n{out.stderr}")
    return json.loads(out.stdout)


_GENERATE = """
import { readFileSync } from "node:fs";
const { contractHash, normalizeContract } = await import(process.env.CONTRACT_JS);
const { generatePythonModule } = await import(process.env.TYPEGEN_JS);
const input = JSON.parse(readFileSync(0, "utf8"));
const out = [];
for (const spec of input) {
  const semanticsVersion = spec.semanticsVersion ?? 2;
  const contract = normalizeContract({ schemaVersion: 1, ...(semanticsVersion !== 1 ? { semanticsVersion } : {}), items: spec.items });
  out.push(generatePythonModule(
    { id: spec.id ?? "crv_one", contentHash: contractHash(contract), semanticsVersion, contract },
    { generatorVersion: "0.11.0-test" },
  ));
}
process.stdout.write(JSON.stringify(out));
"""


def contract_item(name: str, **fields: object) -> dict:
    return {"name": name, "required": {"kind": "never"}, "sensitive": False, "type": "string", **fields}


def generate(*specs: dict) -> "list[str]":
    """Module texts from the real generator: one per {items, id?, semanticsVersion?}."""
    os.environ["CONTRACT_JS"] = "file://" + built("packages/contract/dist/index.js")
    os.environ["TYPEGEN_JS"] = "file://" + built("apps/cli/dist/typegenPython.js")
    return run_node(_GENERATE, list(specs))  # type: ignore[return-value]


_counter = [0]


def load_module(text: str):
    """Import a generated module from a fresh file, as an application would."""
    _counter[0] += 1
    directory = tempfile.mkdtemp(prefix="varlatch-generated-")
    name = f"varlatch_config_{_counter[0]}"
    path = os.path.join(directory, f"{name}.py")
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def context(items: dict, **fields: object) -> str:
    """A run context exactly as `varlatch run --strict` or `--export-context` emits it."""
    return json.dumps(
        {
            "v": 1,
            "mode": "strict",
            "contractRevisionId": "crv_one",
            "contractHash": HASH_A,
            "semanticsVersion": 2,
            "environment": {"rootId": "env_dev", "tier": "development"},
            "items": items,
            **fields,
        }
    )
