# SPDX-License-Identifier: Apache-2.0
# Modules generated by the real CLI generator, imported as an application
# would import them: the vectors through load_config(), and the accessor's
# behaviour (ADR-0038 Decision 13, ADR-0041 Decisions 5 to 8).
import dataclasses
import json
import os
import sys
import traceback
import unittest
import warnings

from _support import (
    ada_available,
    check_ada_mode,
    contract_item,
    context,
    generate,
    load_module,
    CONVERSION_VERSIONS,
    portability,
    semantics,
)

ITEMS = [
    contract_item("API_KEY", sensitive=True, required={"kind": "always"}, description='Key for the "payments" API.\nSecond line \\ with a backslash.'),
    contract_item("DEBUG", type="boolean"),
    contract_item("LOG_LEVEL", type="enum", enumValues=["debug", "info"], defaultValue="info", required={"kind": "always"}),
    contract_item("PORT", type="number", required={"kind": "always"}),
    contract_item("PUBLIC_URL", type="url"),
    contract_item("SENTRY_DSN", required={"kind": "selector", "selector": {"kind": "tier", "tier": "production"}}),
]
VALID = {"API_KEY": "valueaaaaaaaaaaaaa", "DEBUG": "TRUE", "PORT": "8080", "PUBLIC_URL": "https://app.example.com/"}
SECRET = "valueaaaaaaaaaaaaa"


def setUpModule() -> None:
    global MOD
    [text] = generate({"items": ITEMS})
    MOD = load_module(text)


def ctx(items: dict, **fields: object) -> str:
    return context(items, contractHash=MOD.GENERATED_FROM["content_hash"], **fields)


def error(call, module=None):
    """The ConfigError a call raises. Each generated module has its own class."""
    try:
        call()
    except (module or MOD).ConfigError as err:
        return err
    raise AssertionError("expected a ConfigError")


class Types(unittest.TestCase):
    def test_converts_numbers_booleans_enums_and_returns_urls_as_strings(self) -> None:
        config = MOD.load_config(env=VALID).config
        self.assertEqual(config.PORT, 8080)
        self.assertIs(type(config.PORT), int)
        self.assertIs(config.DEBUG, True)
        self.assertEqual(config.PUBLIC_URL, "https://app.example.com/")
        self.assertIsNone(config.LOG_LEVEL)
        self.assertIsNone(config.SENTRY_DSN)

    def test_an_empty_string_is_a_value_never_none(self) -> None:
        config = MOD.load_config(env={**VALID, "API_KEY": ""}).config
        self.assertEqual(config.API_KEY, "")

    def test_annotations(self) -> None:
        hints = {f.name: f.type for f in dataclasses.fields(MOD.Config)}
        self.assertEqual(
            hints,
            {
                "API_KEY": "str",
                "DEBUG": "bool | None",
                # Stored as Python writes the annotation back from its syntax tree.
                "LOG_LEVEL": "_typing.Literal['debug', 'info'] | None",
                "PORT": "float",
                "PUBLIC_URL": "str | None",
                "SENTRY_DSN": "str | None",
            },
        )

    def test_descriptions_become_docstrings_with_quotes_and_backslashes_intact(self) -> None:
        with open(MOD.__file__, encoding="utf-8") as f:
            text = f.read()
        self.assertIn('Key for the \\"payments\\" API.', text)
        self.assertIn("Second line \\\\ with a backslash.", text)


class ReadOnly(unittest.TestCase):
    def test_assignment_and_deletion_raise(self) -> None:
        config = MOD.load_config(env=VALID).config
        with self.assertRaises(dataclasses.FrozenInstanceError):
            config.PORT = 1  # type: ignore[misc]
        with self.assertRaises(dataclasses.FrozenInstanceError):
            del config.PORT  # type: ignore[misc]
        with self.assertRaises((AttributeError, TypeError)):
            config.NEW = 1  # type: ignore[attr-defined]

    def test_sensitive_items_are_kept_out_of_repr_but_not_out_of_asdict(self) -> None:
        config = MOD.load_config(env=VALID).config
        self.assertNotIn(SECRET, repr(config))
        self.assertNotIn("API_KEY", repr(config))
        self.assertIn("PORT=8080", repr(config))
        self.assertEqual(dataclasses.asdict(config)["API_KEY"], SECRET)

    def test_public_has_only_non_sensitive_items(self) -> None:
        public = MOD.load_config(env=VALID).config.public()
        self.assertNotIn("API_KEY", {f.name for f in dataclasses.fields(public)})
        self.assertEqual(public.PORT, 8080)


class InvalidConfiguration(unittest.TestCase):
    def test_one_error_names_every_item_and_reason_and_never_a_value(self) -> None:
        env = {**VALID, "PORT": "80a" + SECRET, "DEBUG": "yes" + SECRET, "PUBLIC_URL": SECRET}
        err = error(lambda: MOD.load_config(env=env))
        self.assertEqual(
            [tuple(i) for i in err.issues],
            [("DEBUG", "must be a boolean"), ("PORT", "must be a number"), ("PUBLIC_URL", "must be a valid URL")],
        )
        self.assertNotIn(SECRET, str(err))
        self.assertIsNone(err.__cause__)
        self.assertIsNone(err.__context__)

    def test_no_frame_of_the_runtime_holds_a_value_or_the_environment_when_it_raises(self) -> None:
        env = {**VALID, "PORT": "not a number " + SECRET}
        err = error(lambda: MOD.load_config(env=env))
        for frame, _ in traceback.walk_tb(err.__traceback__):
            if frame.f_code.co_filename != MOD.__file__:
                continue  # the caller's frames are the caller's (ADR-0041 Decision 7)
            for name, local in frame.f_locals.items():
                self.assertIsNot(local, env, f"{frame.f_code.co_name} holds the environment in {name}")
                self.assertNotIn(SECRET, repr(local), f"{frame.f_code.co_name} holds a value in {name}")

    def test_a_missing_always_required_item_is_an_error(self) -> None:
        env = dict(VALID)
        del env["PORT"]
        err = error(lambda: MOD.load_config(env=env))
        self.assertEqual([tuple(i) for i in err.issues], [("PORT", "required in every environment and absent")])

    def test_a_value_that_is_not_valid_utf8_is_reported(self) -> None:
        err = error(lambda: MOD.load_config(env={**VALID, "API_KEY": "abc\udcff"}))
        self.assertEqual([tuple(i) for i in err.issues], [("API_KEY", "is not valid UTF-8 in the environment")])

    def test_the_lazy_config_raises_the_same_issues_on_every_use(self) -> None:
        [text] = generate({"items": [contract_item("PORT_ONLY", type="number", required={"kind": "always"})]})
        module = load_module(text)
        saved = os.environ.pop("PORT_ONLY", None)
        try:
            first = error(lambda: module.config, module)
            second = error(lambda: module.config, module)
            self.assertEqual(first.issues, second.issues)
        finally:
            if saved is not None:
                os.environ["PORT_ONLY"] = saved


class Environment(unittest.TestCase):
    def test_reads_os_environ_by_default_and_never_writes_to_it(self) -> None:
        [text] = generate({"items": [contract_item("VARLATCH_TEST_LEVEL", type="number", required={"kind": "always"})]})
        module = load_module(text)
        os.environ["VARLATCH_TEST_LEVEL"] = "7"
        try:
            before = dict(os.environ)
            self.assertEqual(module.config.VARLATCH_TEST_LEVEL, 7)
            self.assertEqual(module.load_config().config.VARLATCH_TEST_LEVEL, 7)
            self.assertEqual(dict(os.environ), before)
        finally:
            del os.environ["VARLATCH_TEST_LEVEL"]

    def test_never_writes_to_a_given_mapping(self) -> None:
        env = {**VALID, "VARLATCH_RUN_CONTEXT": ctx({}, mode="exported")}
        before = dict(env)
        MOD.load_config(env=env, apply_defaults=True)
        self.assertEqual(env, before)


class Defaults(unittest.TestCase):
    def test_none_are_applied_unless_asked_and_then_they_are_reported(self) -> None:
        self.assertIsNone(MOD.load_config(env=VALID).config.LOG_LEVEL)
        result = MOD.load_config(env=VALID, apply_defaults=True)
        self.assertEqual(result.config.LOG_LEVEL, "info")
        self.assertEqual(result.defaulted, ("LOG_LEVEL",))

    def test_never_after_a_strict_run(self) -> None:
        env = {**VALID, "VARLATCH_RUN_CONTEXT": ctx({"LOG_LEVEL": {"server": "notStored", "delivery": "absent"}})}
        err = error(lambda: MOD.load_config(env=env, apply_defaults=True))
        self.assertEqual([tuple(i) for i in err.issues], [("LOG_LEVEL", "required in this environment and absent")])

    def test_never_for_an_item_the_server_withheld(self) -> None:
        env = {
            **VALID,
            "VARLATCH_RUN_CONTEXT": ctx({"LOG_LEVEL": {"server": "withheld", "delivery": "absent"}}, mode="exported"),
        }
        err = error(lambda: MOD.load_config(env=env, apply_defaults=True))
        self.assertEqual(
            [tuple(i) for i in err.issues],
            [("LOG_LEVEL", "required in this environment, withheld by the server, and absent")],
        )


class RunContext(unittest.TestCase):
    def test_a_withheld_value_supplied_by_an_allowed_inherited_value_is_returned(self) -> None:
        env = {**VALID, "VARLATCH_RUN_CONTEXT": ctx({"API_KEY": {"server": "withheld", "delivery": "inherited"}})}
        env["LOG_LEVEL"] = "debug"
        self.assertEqual(MOD.load_config(env=env).config.API_KEY, SECRET)

    def test_per_environment_requiredness(self) -> None:
        production = {"rootId": "env_prod", "tier": "production"}
        env = {**VALID, "LOG_LEVEL": "info", "VARLATCH_RUN_CONTEXT": ctx({}, environment=production)}
        err = error(lambda: MOD.load_config(env=env))
        self.assertEqual([tuple(i) for i in err.issues], [("SENTRY_DSN", "required in this environment and absent")])
        development = {**env, "VARLATCH_RUN_CONTEXT": ctx({})}
        self.assertEqual(MOD.load_config(env=development).context, "strict")

    def test_without_a_context_conditional_items_are_not_evaluated(self) -> None:
        self.assertEqual(MOD.load_config(env=VALID).not_evaluated, ("SENTRY_DSN",))
        err = error(lambda: MOD.load_config(env=VALID, require_context=True))
        self.assertEqual(err.issues[0].name, "VARLATCH_RUN_CONTEXT")

    def test_stale_types_warn_by_default_and_raise_on_request(self) -> None:
        stale = {**VALID, "VARLATCH_RUN_CONTEXT": context({}, mode="exported", contractHash="sha256:" + "b" * 64)}
        seen: "list[str]" = []
        result = MOD.load_config(env=stale, on_warning=seen.append)
        self.assertEqual(len(seen), 1)
        self.assertIn("the types are stale", seen[0])
        self.assertEqual(result.warnings, tuple(seen))
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            MOD.load_config(env=stale)
        self.assertTrue(any(issubclass(w.category, MOD.VarlatchWarning) for w in caught))
        err = error(lambda: MOD.load_config(env=stale, stale_types="raise"))
        self.assertEqual(err.issues[0].name, "VARLATCH_RUN_CONTEXT")

    def test_a_different_semantics_version_raises(self) -> None:
        env = {**VALID, "VARLATCH_RUN_CONTEXT": ctx({}, semanticsVersion=1)}
        err = error(lambda: MOD.load_config(env=env))
        self.assertEqual(
            err.issues[0].reason,
            "names Contract Semantics version 1, but these types use version 2; regenerate them with varlatch types",
        )

    def test_rejects_an_unknown_stale_types_option(self) -> None:
        with self.assertRaises(ValueError):
            MOD.load_config(env=VALID, stale_types="ignore")  # type: ignore[arg-type]


class VectorsThroughTheGeneratedModule(unittest.TestCase):
    def test_every_validate_vector(self) -> None:
        check_ada_mode(self)
        for version in CONVERSION_VERSIONS:
            self.check_version(version)

    def check_version(self, version: int) -> None:
        vectors = semantics(version)["validate"] + portability(version)["validate"]
        specs = []
        for v in vectors:
            fields = {"type": v["type"]}
            if "enumValues" in v:
                fields["enumValues"] = v["enumValues"]
            specs.append({"items": [contract_item("ITEM", **fields)], "semanticsVersion": version})
        # One module per distinct item shape.
        shapes = {json.dumps(s, sort_keys=True): s for s in specs}
        modules = dict(zip(shapes, (load_module(t) for t in generate(*shapes.values()))))
        for v, spec in zip(vectors, specs):
            module = modules[json.dumps(spec, sort_keys=True)]
            with self.subTest(version=version, type=v["type"], value=v["value"]):
                if v.get("internationalizedHost") and not ada_available():
                    err = error(lambda: module.load_config(env={"ITEM": v["value"]}), module)
                    self.assertEqual(err.issues[0].reason, "is an internationalized URL; install the ada-url package to validate it")
                elif not v["valid"]:
                    err = error(lambda: module.load_config(env={"ITEM": v["value"]}), module)
                    self.assertEqual([tuple(i) for i in err.issues], [("ITEM", v["reason"])])
                else:
                    value = module.load_config(env={"ITEM": v["value"]}).config.ITEM
                    expected = v["converted"]
                    if "number" in expected and v["type"] == "integer":
                        self.assertIs(type(value), int)
                        self.assertEqual(value, int(expected["number"]))
                    elif "number" in expected:
                        self.assertEqual(value, float(expected["number"]))
                    elif "boolean" in expected:
                        self.assertIs(value, expected["boolean"])
                    else:
                        self.assertEqual(value, expected["string"])

    def test_every_requiredness_vector_through_run_contexts(self) -> None:
        for i, v in enumerate(semantics(3)["required"]):
            fields = {"required": v["required"]}
            if "defaultValue" in v:
                fields["defaultValue"] = v["defaultValue"]
            [text] = generate({"items": [contract_item("ITEM", **fields)]})
            module = load_module(text)
            content_hash = module.GENERATED_FROM["content_hash"]

            def fails(mode: str, server: str) -> bool:
                raw = context(
                    {"ITEM": {"server": server, "delivery": "absent"}},
                    mode=mode,
                    environment=v["environment"],
                    contractHash=content_hash,
                )
                try:
                    module.load_config(env={"VARLATCH_RUN_CONTEXT": raw})
                    return False
                except module.ConfigError:
                    return True

            with self.subTest(vector=i):
                self.assertIs(fails("strict", "notStored"), v["requiredApplies"])
                self.assertIs(fails("exported", "notStored"), v["missingWhenAbsent"])
                self.assertIs(fails("exported", "withheld"), v["requiredApplies"])


class Refusals(unittest.TestCase):
    def test_version_1_is_refused_by_the_generator(self) -> None:
        with self.assertRaises(AssertionError) as caught:
            generate({"items": [contract_item("ITEM")], "semanticsVersion": 1})
        self.assertIn("defines no conversion", str(caught.exception))


if __name__ == "__main__":
    unittest.main()


class Integers(unittest.TestCase):
    """The integer type (semantics version 3): annotated and returned as int."""

    def test_annotation_value_and_refusals(self) -> None:
        [text] = generate(
            {
                "items": [
                    contract_item("PORT", type="integer", required={"kind": "always"}),
                    contract_item("RATIO", type="number"),
                ],
                "semanticsVersion": 3,
            }
        )
        module = load_module(text)
        hints = {f.name: f.type for f in dataclasses.fields(module.Config)}
        self.assertEqual(hints["PORT"], "int")
        self.assertEqual(hints["RATIO"], "float | None")
        config = module.load_config(env={"PORT": "3000", "RATIO": "3.5"}).config
        self.assertIs(type(config.PORT), int)
        self.assertEqual(config.PORT, 3000)
        self.assertEqual(config.RATIO, 3.5)
        for bad in ("3.0", "3.5", "+1", "1e3"):
            err = error(lambda: module.load_config(env={"PORT": bad}), module)
            self.assertEqual([tuple(i) for i in err.issues], [("PORT", "must be a whole number")])
        with open(module.__file__, encoding="utf-8") as f:
            self.assertIn("A whole number.", f.read())

